language: rust
rust:
  - stable
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - RUSTFLAGS='-F warnings' cargo build --all
  - cargo build --examples --all
stages:
  - Check
  - Test
jobs:
  include:
    - stage: Check
      name: Format
      script:
        - cargo fmt --all -- --check
    - stage: Check
      name: Clippy
      script:
        - make clippy
    - stage: Test
      name: Unitest(molc)
      script:
        - RUSTFLAGS='-F warnings' RUST_BACKTRACE=full cargo test --all --features molc
    - stage: Test
      name: Bench(molc)
      script:
        - cd bench
        - cargo run --release --features molc
    - stage: Test
      name: Unitest(flatc)
      script:
        - RUSTFLAGS='-F warnings' RUST_BACKTRACE=full cargo test --all --features flatc
    - stage: Test
      name: Bench(flatc)
      script:
        - cd bench
        - cargo run --release --features flatc
