[package]
name = "libp2p-rs"
version = "0.1.0"
license = "MIT"
description = "Minimal implementation for a multiplexed p2p network framework."
authors = ["kingwel-xie <kingwel.xie@139.com>"]
repository = "https://github.com/pld/libp2p-rs"
include = ["Cargo.toml", "src/*", "README.md", "LICENSE"]
readme = "README.md"
keywords = ["network", "peer-to-peer"]
categories = ["network-programming", "asynchronous"]
edition = "2018"

[package.metadata.docs.rs]
all-features = false
no-default-features = true

[dependencies]
yamux = { path = "yamux", version = "0.1.0", package = "yamux" }
secio = { path = "secio", version = "0.1.0", package = "secio" }
multiaddr = { path = "multiaddr", package = "multiaddr", version = "0.1.0" }


async-std = { version = "1.6.2", features = ["attributes", "unstable"] }
futures = { version = "0.3.5" }
pin-project-lite = "0.1"
log = "0.4"
bytes = "0.5.0"
thiserror = "1.0"
molecule = { version = "0.6.0" }

# upnp
igd = "0.9"

[target.'cfg(unix)'.dependencies.libc]
version = "0.2"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.7"
features = ["minwindef", "ws2def", "winerror", "heapapi"]

[dev-dependencies]
env_logger = "0.6.0"
crossbeam-channel = "0.3.6"
systemstat = "0.1.3"
futures-test = "0.3.5"

[target.'cfg(unix)'.dev-dependencies]
nix = "0.13.0"

[workspace]
members = [
  "yamux",
  "secio",
#  "multiaddr",
#  "bench",
]
exclude = [
  "protocols/discovery",
  "protocols/identify",
  "protocols/ping",
]
