[package]
name = "libp2p-rs"
version = "0.1.0"
license = "MIT"
description = "Minimal implementation for a multiplexed p2p network framework."
authors = ["kingwel-xie <kingwel.xie@139.com>"]
repository = "https://github.com/pld/libp2p-rs"
include = ["Cargo.toml", "src/*", "README.md", "LICENSE"]
readme = "README.md"
keywords = ["network", "peer-to-peer"]
categories = ["network-programming", "asynchronous"]
edition = "2018"

[package.metadata.docs.rs]
all-features = false
no-default-features = true

[dependencies]
libp2p-traits = { path = "traits", version = "0.1.0", package = "libp2p-traits" }
yamux = { path = "protocols/yamux", version = "0.1.0", package = "yamux" }
mplex = { path = "protocols/mplex", version = "0.1.0", package = "mplex" }
secio = { path = "protocols/secio", version = "0.1.0", package = "secio" }
multiaddr = { path = "multiaddr", package = "parity-multiaddr", version = "0.9.1" }
libp2p-core = { path = "core", version = "0.1.0", package = "libp2p-core" }
libp2p-tcp = { path = "transports/tcp", version = "0.0.1", package = "libp2p-tcp" }
libp2p-swarm = { path = "swarm", version = "0.1.0", package = "libp2p-swarm" }


async-std = { version = "1.6", features = ["attributes", "unstable"] }
async-trait = "0.1"
futures = { version = "0.3.5" }
pin-project-lite = "0.1"
log = "0.4"
bytes = "0.5.0"

# upnp
igd = "0.9"

[target.'cfg(unix)'.dependencies.libc]
version = "0.2"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.7"
features = ["minwindef", "ws2def", "winerror", "heapapi"]

[dev-dependencies]
env_logger = "0.6.0"
crossbeam-channel = "0.3.6"
systemstat = "0.1.3"
futures-test = "0.3.5"
secp256k1 = "0.17"
rand = "0.7"
lazy_static = "1.4"


[target.'cfg(unix)'.dev-dependencies]
nix = "0.13.0"

[workspace]
members = [
  "traits",
  "protocols/yamux",
  "protocols/mplex",
  "protocols/secio",
  "protocols/plaintext",
  "core",
  "transports/tcp",
  "multiaddr",
  "swarm",
]

[[example]]
name = "secio_simple"
path = "protocols/secio/examples/secio_simple.rs"
[[example]]
name = "simple"
path = "examples/simple.rs"