[package]
name = "libp2prs-plaintext"
version = "0.2.0"
license = "MIT"
description = "Plaintext encryption dummy protocol for libp2p "
authors = ["Netwarps Technologies admin@paradeum.com"]
repository = "https://github.com/netwarps/libp2p-rs"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]
edition = "2018"

[dependencies]
libp2prs-core = { path = "../../core", version = "0.2.0", package = "libp2prs-core" }
libp2prs-traits = { path = "../../traits", version = "0.2.0", package = "libp2prs-traits" }
bytes = "0.5"
futures = "0.3.0"
log = "0.4.1"
async-trait = "0.1"
prost = "0.6.1"
secp256k1 = "0.17"


[dev-dependencies]
env_logger = "0.6"
criterion = "0.3"
async-std = "1.6"

[build-dependencies]
prost-build = "0.6"