[package]
name = "libp2p-swarm"
edition = "2018"
description = "The libp2p swarm"
version = "0.1.0"
authors = ["netwarps"]
license = "MIT"
repository = ""
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
futures = "0.3"
libp2p-core = { version = "0.1.0", path = "../core" }
log = "0.4"
rand = "0.7"
smallvec = "1.0"
wasm-timer = "0.2"
void = "1"

[dev-dependencies]
#libp2p-mplex = { path = "../muxer/mplex" }
quickcheck = "0.9.0"
rand = "0.7.2"
