[package]
name = "libp2p-dns"
version = "0.1.0"
license = "MIT"
description = "DNS transport implementation for libp2p"
authors = ["Netwarps Technologies admin@paradeum.com"]
repository = "https://github.com/netwarps/libp2p-rs"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]
edition = "2018"

[dependencies]
libp2p-core = { version = "0.1.0", path = "../../core" }
log = "0.4"
futures = "0.3.5"
async-std = "1.6"
async-trait = "0.1"

[dev-dependencies]
libp2p-traits = { path = "../../traits", version = "0.1.0", package = "libp2p-traits" }
libp2p-tcp = { path = "../tcp", version = "0.1.0", package = "libp2p-tcp" }
multiaddr = { path = "../../multiaddr", package = "parity-multiaddr", version = "0.1.0" }