[package]
name = "yamux"
version = "0.1.0"
license = "MIT"
description = "Mplex multiplexing protocol for libp2p"
authors = ["Netwarps Technologies admin@paradeum.com"]
repository = "https://github.com/netwarps/libp2p-rs"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]
edition = "2018"

[[bench]]
name = "concurrent"
harness = false

[dependencies]
libp2p-core = { path = "../../core", version = "0.1.0", package = "libp2p-core" }
libp2p-traits = { path = "../../traits", version = "0.1.0", package = "libp2p-traits" }
async-trait = "0.1"
log = "0.4.8"
async-std = "1.6"
bytes = "0.5.6"

[dependencies.futures]
version = "0.3.4"
features = ["std"]
default-features = false

[dependencies.nohash-hasher]
version = "0.2"

[dependencies.rand]
version = "0.7.2"

[dependencies.static_assertions]
version = "1"

[dev-dependencies.anyhow]
version = "1"

[dev-dependencies.async-std]
version = "1.6.2"

[dev-dependencies.criterion]
version = "0.3"

[dev-dependencies.futures]
version = "0.3.5"

[dev-dependencies.env_logger]
version = "0.6"

[dev-dependencies.quickcheck]
version = "0.9"

[dev-dependencies.secio]
path = "../secio"

[dev-dependencies.libp2p-core]
path = "../../core"
version = "0.1.0"
package = "libp2p-core"

[dev-dependencies.bytesize]
version = "1.0.1"
