name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  fmt_clippy_docs:
    name: Checking fmt, clippy, and docs
    runs-on: [self-hosted, linux, X64]
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.48
        override: true

    - name: setup
      run: |
        rustup component add clippy rustfmt
        rustc --version

    - name: clippy
      run: RUSTFLAGS='-F warnings' cargo clippy --all --examples --tests
   
    - name: fmt
      run: cargo fmt --all -- --check
      
    - name: docs
      run: cargo doc
  
  build_and_test:
    name: Build and test
    needs: [fmt_clippy_docs]
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [[self-hosted, linux, X64],[self-hosted, windows, X64]]
        rust: [1.47.0]

    steps:
    - uses: actions/checkout@v1

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    
    - name: Build
      run: cargo build --release --examples --all
    - name: Unit test
      run: cargo test --all
    - name: Bench test
      run: cargo bench --all