name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  fmt_clippy_docs:
    name: Checking fmt, clippy, and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: setup
      run: |
        rustup component add clippy rustfmt
        rustc --version

    - name: clippy
      run: RUSTFLAGS='-F warnings' cargo clippy --all --examples --tests
   
    - name: fmt
      run: cargo fmt --all -- --check
      
    - name: docs
      run: cargo doc
  
  build_and_test:
    name: Build and test
    needs: [fmt_clippy_docs]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        rust: [1.46.0,1.47.0]

    steps:
    - uses: actions/checkout@v1

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    
    - uses: actions/checkout@v1
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ hashFiles('Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: cargo-index-${{ hashFiles('Cargo.toml') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: cargo-build-target-${{ hashFiles('Cargo.toml') }}
    - name: build
      run: cargo build --examples --all
    - name: Unit test
      run: cargo test --all
    - name: bench test
      run: cargo bench --all